language: python
dist: xenial
install:
    - "python -m pip install pluggy==0.9.0"
    - "python -m pip install codecov==2.0.15"
    - "make install-test"
cache: pip
jobs:
  include:
    - stage: test
      script:
        - "make test-ci"
      python: "2.7"
    - stage: test
      script:
        - "make test-ci"
      python: "3.4"
    - stage: test
      script:
        - "make test-ci"
      python: "3.5"
    - stage: test
      script:
        - "make test-ci"
      python: "3.6"
    - stage: test
      script:
        - "make test-ci"
      python: "3.7"
after_success:
    - codecov

