language: python
dist: xenial
before_install:
    - "sudo apt-get install -qq -y python-dev"
    - "sudo apt-get install -qq -y python3-dev"
install:
    - "python -m pip install codecov==2.0.15"
    - "make install-tests"
cache: pip
jobs:
  include:
    - stage: test
      script:
        - "make test"
      python: "2.7"
    - stage: test
      script:
        - "make test"
      python: "3.4"
    - stage: test
      script:
        - "make test"
      python: "3.5"
    - stage: test
      script:
        - "make test"
      python: "3.6"
    - stage: test
      script:
        - "make test"
      python: "3.7"
    - stage: test
      script:
        - "make test"
      python: "pypy"
    - stage: test
      script:
        - "make test"
      python: "pypy3"
after_success:
    - codecov

