language: python
dist: xenial
install:
    - "make install-test"
jobs:
  include:
    - stage: test
      script:
        - "make test-ci"
      python: "2.7"
    - stage: test
      script:
        - "make test-ci"
      python: "3.4"
    - stage: test
      script:
        - "make test-ci"
      python: "3.5"
    - stage: test
      script:
        - "make test-ci"
      python: "3.6"
    - stage: test
      script:
        - "make test-ci"
      python: "3.7"
after_success:
  - codecov

