dist: xenial
language: python
cache: pip

stages:
    - test

services:
    - postgresql

install:
    - "sudo apt-get install -y python-dev"
    - "sudo apt-get install -y python3-dev"
    - "python -m pip install codecov"
    - "make install-tests"

before_script:
    - psql -c 'create database travis_ci_test;' -U postgres

jobs:
  include:
    - stage: test
      python: "2.7"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "3.4"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "3.5"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "3.6"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "3.7"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "3.8-dev"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "pypy"
      script:
        - "make test"
        - "make test-postgresql"
    - stage: test
      python: "pypy3"
      script:
        - "make test"
        - "make test-postgresql"

after_success:
    - codecov
