language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "pip install -e .[test]"
install:
  - "pip install -r requirements.txt"
script:
  - "python -m pytest ./tests/test_*.py --cov snippy -vv"
after_success:
  - codecov
