language: python
python:
        #  - "2.7"
        #  - "3.4"
  - "3.5"
    #  - "3.6"
before_install:
  - sudo apt-get install -y gdb python-dbg
  - "pip install -e .[test]"
install:
  - "pip install -r requirements.txt"
before_script:
  - ulimit -c unlimited -S
script:
# - "python -m pytest ./tests/test_*.py --cov snippy -vv"
  - "gdb -ex r --args python -m pytest ./tests/test_wf_import_solution.py --cov snippy -vv"
after_success:
  - codecov
after_failure:
  - ls -al
  - pwd
  - find / -name '*core*'
  - COREFILE=$(find . -maxdepth 1 -name "core" | head -n 1) # find core file
  - if [[ -f "$COREFILE" ]]; then gdb -c "$COREFILE" example -ex "thread apply all bt" -ex "set pagination 0" -batch; fi
  - gdb -c ./core example -ex "thread apply all py-list" -ex "set pagination 0" -batch
  - gdb -c ./core example -ex "py-list" -ex "set pagination 0" -batch

