openapi: 3.0.0
servers:
  - url: /api/v1
info:
  description: Snippy REST API
  version: "1.0.0-oas3"
  title: Snippy REST API
  termsOfService: 'https://github.com/heilaaks/snippy'
  contact:
    email: laaksonen.heikki.j@gmail.com
  license:
    name: Apache 2.0
    url: 'https://github.com/heilaaks/snippy/blob/master/LICENSE'
paths:
  /snippets:
    post:
      tags:
        - snippet
      summary: Add new snippet
      description: ''
      responses:
        '201':
          description: Snippet created
        '405':
          description: Invalid input
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
        description: New snippet that is stored
        required: true
    get:
      tags:
        - snippet
      summary: Search snippets
      description: ''
      parameters:
        - name: sall
          in: query
          required: false
          description: Search keywords from all fields.
          schema:
            type: array
            items:
              type: string
        - name: stag
          in: query
          required: false
          description: Search keywords only from tag field.
          schema:
            type: array
            items:
              type: string
        - name: sgrp
          in: query
          required: false
          description: Search keywords only from group field.
          schema:
            type: array
            items:
              type: string
        - name: digest
          in: query
          required: false
          description: Search only based on message digest field.
          schema:
            type: string
        - name: data
          in: query
          required: false
          description: Search only from content data.
          schema:
            type: string
        - name: filter
          in: query
          required: false
          description: Filter search result with provided regexp.
          schema:
            type: string
        - name: limit
          in: query
          required: false
          description: Limit query result list.
          schema:
            type: integer
            default: 20
        - name: sort
          in: query
          required: false
          description: Sort based on defined field.
          schema:
            type: string
            enum:
              - data
              - brief
              - group
              - tags
              - links
              - category
              - filename
              - runalias
              - versions
              - utc
              - digest
              - key
            default: brief
        - name: fields
          in: query
          required: false
          description: Limit fields that are returned in result list.
          schema:
            type: array
            items:
              type: string
              enum:
                - data
                - brief
                - group
                - tags
                - links
                - category
                - filename
                - runalias
                - versions
                - utc
                - digest
                - key
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
            application/text:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
            application/yaml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
        '400':
          description: Request not syntactically correct
        '404':
          description: Snippet not found
    delete:
      tags:
        - snippet
      summary: Delete one snippet
      description: ''
      parameters:
        - name: sall
          in: query
          required: false
          description: Search keywords from all fields.
          schema:
            type: array
            items:
              type: string
        - name: stag
          in: query
          required: false
          description: Search keywords only from tag field.
          schema:
            type: array
            items:
              type: string
        - name: sgrp
          in: query
          required: false
          description: Search keywords only from group field.
          schema:
            type: array
            items:
              type: string
        - name: digest
          in: query
          required: false
          description: Search only based on message digest.
          schema:
            type: string
        - name: data
          in: query
          required: false
          description: Search only from content data.
          schema:
            type: string
      responses:
        '204':
          description: Snippet deleted
        '400':
          description: Request not syntactically correct
        '404':
          description: Snippet not found
        '405':
          description: More than one snippet found
  '/snippets/{digest}':
    put:
      tags:
        - snippet
      summary: Update defined snippet
      description: ''
      parameters:
        - name: digest
          in: path
          required: true
          description: Unique snippet identified by message digest.
          x-example: 44afdd0c59e17159
          schema:
            type: string
      responses:
        '201':
          description: Snippet updated
        '400':
          description: Request not syntactically correct
        '404':
          description: Snippet not found
        '405':
          description: Validation exception
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Content'
        description: Existing snippet that is updated
        required: true
    get:
      tags:
        - snippet
      summary: Get snippet with digest
      description: ''
      parameters:
        - name: digest
          in: path
          required: true
          description: Unique snippet identified by message digest.
          x-example: 44afdd0c59e17159
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
        '400':
          description: Request not syntactically correct
        '404':
          description: Snippet not found
    delete:
      tags:
        - snippet
      summary: Delete snippet with digest
      description: ''
      parameters:
        - name: digest
          in: path
          required: true
          description: Unique snippet identified by message digest.
          x-example: 44afdd0c59e17159
          schema:
            type: string
      responses:
        '204':
          description: Snippet deleted
        '404':
          description: Snippet not found
        '405':
          description: More than one snippet found
components:
  schemas:
    Content:
      type: object
      properties:
        data:
          type: string
          description: Mandatory content data.
        brief:
          type: string
          description: Brief description of the content.
        group:
          type: string
          description: Single group to which the content belongs.
        tags:
          type: array
          items:
            type: string
          description: Comma separated list of tags.
        links:
          type: array
          items:
            type: string
          description: Comma separated list of refrence links.
        category:
          type: string
          enum:
            - snippet
            - solution
          description: Automatically defined content category.
        filename:
          type: string
          description: >-
            Optional filename that that defines automatically used filename when
            content is exported.
        runalias:
          type: string
          description: Optional alias to run the content.
        versions:
          type: string
          description: Optional list of services and versions related to the snippet.
        utc:
          type: string
          description: Optional UTC timestamp that is automatically assigned if left out.
        digest:
          type: string
          description: >-
            Automatically assigned message digest that uniquely identifies the
            content.
        metadata:
          type: string
          description: Automatically assigned internal metadata.
        key:
          type: string
          description: Automatically assigned internal contentn key.
      required:
        - data
    Search:
      type: object
      properties:
        sall:
          type: array
          items:
            type: string
          description: Search keywords from all fields.
        stag:
          type: array
          items:
            type: string
          description: Search keywords only from tag field.
        sgrp:
          type: array
          items:
            type: string
          description: Search keywords only from group field.
        digest:
          type: string
          description: Search only based on message digest.
        data:
          type: string
          description: Search only from content data.
        filter:
          type: string
          description: Filter search result with regexp.
